# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    - pull_request

name: "Code style"

jobs:
    run:
        name: "CI"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ["7.4"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@2.22.0
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: gd,mbstring,pcov
                  tools: cs2pr

            - name: Install dependencies
              uses: ramsey/composer-install@v2

            - name: Run Grumphp
              run: vendor/bin/grumphp run --testsuite=cs -n

            - name: Send feedback on Github
              if: ${{ failure() }}
              run: |
                  vendor/bin/php-cs-fixer --allow-risky=yes --config=.php_cs.dist fix --dry-run --format=checkstyle | cs2pr
