# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    push:
    pull_request:

name: "Static analysis"

jobs:
    run:
        name: "CI"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macOS-latest]
                php-versions: ["7.4"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@2.18.1
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: gd,mbstring,pcov,xdebug
                  tools: cs2pr

            - name: Install dependencies
              uses: ramsey/composer-install@v2

            - name: Run Grumphp
              run: vendor/bin/grumphp run --tasks=psalm,phpstan -n

            - name: Send feedback on Github
              if: ${{ failure() }}
              run: |
                  vendor/bin/phpstan analyse -l max --error-format=checkstyle src/ | cs2pr
                  vendor/bin/psalm --output-format=github | cs2pr

            - name: Send PSALM data
              run: vendor/bin/psalm --shepherd --stats src/
              continue-on-error: true
